view:
    layout_view:
        default:
            layout_nt:
                template: "@App/nglayouts/themes/app/layout/layout_nt.html.twig"
                match:
                    layout\type: layout_nt
        app:
            layout_nt:
                template: "@App/nglayouts/app/layout/layout_nt.html.twig"
                match:
                    layout\type: layout_nt
